<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      DB::table('events')->insert([
        [
          'title' => 'Hology Developer Competition',
          'description' => 'Kompetisi pengembangan aplikasi bagi para developer yang ingin menguji kemampuan dalam menciptakan solusi digital inovatif. Peserta akan ditantang untuk merancang, membangun, dan mempresentasikan produk berbasis teknologi secara profesional.',
          'short_description' => 'Lomba developer untuk menciptakan solusi digital inovatif',
          'event_start' => Carbon::parse('2026-11-10 09:00'),
          'event_end' => Carbon::parse('2026-11-10 17:00'),
          'location' => 'FILKOM UB',
          'quota' => 100,
          'quota_filled' => 60,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 0,
          'is_paid' => false,
          'category_id' => 1,
          'created_by' => 1,
          'image_url' => 'assets/events/Hology.png',
          'organizer' => 'BEM FILKOM',
          'contact_email' => 'bem@ub.ac.id',
          'contact_phone' => '628123456789',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Talent Tari Mahasiswa',
          'description' => 'Ajang unjuk bakat di bidang seni tari yang memberikan ruang bagi mahasiswa untuk mengekspresikan kreativitas dan keindahan gerak. Terbuka untuk individu maupun kelompok dengan berbagai konsep pertunjukan.',
          'short_description' => 'Ajang bakat tari untuk mahasiswa kreatif',
          'event_start' => Carbon::parse('2026-11-12 13:00'),
          'event_end' => Carbon::parse('2026-11-12 17:00'),
          'location' => 'Gedung Samantha Krida UB',
          'quota' => 80,
          'quota_filled' => 40,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 25000,
          'is_paid' => true,
          'category_id' => 2,
          'created_by' => 1,
          'image_url' => 'assets/events/Talent_Tari.jpeg',
          'organizer' => 'UKM Seni UB',
          'contact_email' => 'seni@ub.ac.id',
          'contact_phone' => '628987654321',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Turnamen Bulu Tangkis UB',
          'description' => 'Kompetisi olahraga bulu tangkis yang mempertemukan para pemain berbakat dalam pertandingan yang kompetitif dan sportif. Cocok untuk mahasiswa yang ingin menunjukkan kemampuan sekaligus menjunjung tinggi fair play.',
          'short_description' => 'Turnamen bulu tangkis penuh sportivitas',
          'event_start' => Carbon::parse('2026-11-15 08:00'),
          'event_end' => Carbon::parse('2026-11-15 14:00'),
          'location' => 'GOR Pertamina UB',
          'quota' => 64,
          'quota_filled' => 32,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 30000,
          'is_paid' => true,
          'category_id' => 3,
          'created_by' => 1,
          'image_url' => 'assets/events/UABT.jpeg',
          'organizer' => 'UKM Olahraga',
          'contact_email' => 'olahraga@ub.ac.id',
          'contact_phone' => '6281122334455',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Brawijaya Esport Tournament',
          'description' => 'Turnamen game yang diselenggarakan oleh komunitas Brawijaya Esport, menghadirkan persaingan sengit antar pemain dalam berbagai judul game populer. Wadah bagi gamer untuk menunjukkan strategi, kerja tim, dan skill terbaiknya.',
          'short_description' => 'Turnamen game kompetitif antar mahasiswa',
          'event_start' => Carbon::parse('2026-11-18 10:00'),
          'event_end' => Carbon::parse('2026-11-18 18:00'),
          'location' => 'Gedung Kreatif UB',
          'quota' => 120,
          'quota_filled' => 90,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 20000,
          'is_paid' => true,
          'category_id' => 4,
          'created_by' => 1,
          'image_url' => 'assets/events/BEST.jpeg',
          'organizer' => 'Brawijaya Esport',
          'contact_email' => 'esport@ub.ac.id',
          'contact_phone' => '6285566778899',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Kompetisi Bisnis PO Makanan',
          'description' => 'Kompetisi kewirausahaan yang berfokus pada pengembangan ide bisnis pre-order makanan. Peserta akan belajar merancang strategi pemasaran, operasional, hingga pengelolaan keuntungan secara nyata.',
          'short_description' => 'Lomba bisnis kreatif berbasis PO makanan',
          'event_start' => Carbon::parse('2026-11-20 09:00'),
          'event_end' => Carbon::parse('2026-11-20 15:00'),
          'location' => 'FILKOM UB',
          'quota' => 50,
          'quota_filled' => 20,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 15000,
          'is_paid' => true,
          'category_id' => 5,
          'created_by' => 1,
          'image_url' => 'assets/events/Bisnis.jpeg',
          'organizer' => 'HMDTIF',
          'contact_email' => 'hmdtif@ub.ac.id',
          'contact_phone' => '6289988776655',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Lomba Esai Nasional',
          'description' => 'Ajang kompetisi penulisan esai tingkat nasional yang mengajak peserta untuk menuangkan gagasan kritis dan solutif terhadap berbagai isu terkini. Cocok bagi mahasiswa yang gemar menulis dan berpikir analitis.',
          'short_description' => 'Kompetisi esai nasional penuh gagasan kritis',
          'event_start' => Carbon::parse('2026-11-22 08:00'),
          'event_end' => Carbon::parse('2026-11-22 12:00'),
          'location' => 'Online',
          'quota' => 200,
          'quota_filled' => 120,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 10000,
          'is_paid' => true,
          'category_id' => 6,
          'created_by' => 1,
          'image_url' => 'assets/events/NESC.jpeg',
          'organizer' => 'Panitia Nasional',
          'contact_email' => 'esai@event.id',
          'contact_phone' => '6283344556677',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Beasiswa Djarum 2026',
          'description' => 'Program beasiswa yang memberikan dukungan finansial sekaligus pembinaan karakter bagi mahasiswa berprestasi. Tidak hanya bantuan pendidikan, tetapi juga kesempatan untuk mengembangkan soft skill dan jaringan.',
          'short_description' => 'Program beasiswa untuk mahasiswa berprestasi',
          'event_start' => Carbon::parse('2026-11-25 09:00'),
          'event_end' => Carbon::parse('2026-11-25 12:00'),
          'location' => 'Online',
          'quota' => 300,
          'quota_filled' => 150,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 0,
          'is_paid' => false,
          'category_id' => 7,
          'created_by' => 1,
          'image_url' => 'assets/events/Djarum.jpeg',
          'organizer' => 'Djarum Foundation',
          'contact_email' => 'info@djarum.org',
          'contact_phone' => '6282233445566',
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'title' => 'Pengambilan Terakhir Jaket Angkatan',
          'description' => 'Kesempatan terakhir bagi mahasiswa untuk mengambil jaket angkatan yang telah dipesan. Pastikan tidak melewatkan momen ini sebagai bagian dari identitas dan kebersamaan satu angkatan.',
          'short_description' => 'Pengambilan terakhir jaket angkatan',
          'event_start' => Carbon::parse('2026-11-28 10:00'),
          'event_end' => Carbon::parse('2026-11-28 16:00'),
          'location' => 'Sekretariat Fakultas',
          'quota' => 500,
          'quota_filled' => 300,
          'event_status' => 'Dibuka',
          'registration_status' => 'Terdaftar',
          'price' => 0,
          'is_paid' => false,
          'category_id' => 8,
          'created_by' => 1,
          'image_url' => 'assets/events/Jakang.jpeg',
          'organizer' => 'Panitia Angkatan',
          'contact_email' => 'angkatan@ub.ac.id',
          'contact_phone' => '6284455667788',
          'created_at' => now(),
          'updated_at' => now(),
        ],
      ]);
    }
}
